### ISSUE TITLE
Sorting the toggles in the display

### ISSUE THREAD

**Issue by boomboompower** [boomboompower/ToggleChat#20]
Users should be able to choose which toggles come first

**Comment by Moire9** [comment]
I don't know if this is possible with the current sorting system, but perhaps we could define "groups" that are sorted in a fixed order, and the group that a toggle is in is set in it's class. The toggles in the same group would be together, and then the groups could be sorted some other way. For example, we could have the different chats toggles (guild, global, build battle, etc), and then the join/leave notifications could be together, etc.

**Comment by boomboompower** [comment]
> I don't know if this is possible with the current sorting system, but perhaps we could define "groups" that are sorted in a fixed order, and the group that a toggle is in is set in it's class. The toggles in the same group would be together, and then the groups could be sorted some other way. For example, we could have the different chats toggles (guild, global, build battle, etc), and then the join/leave notifications could be together, etc.

This has been implemented in https://github.com/boomboompower/ToggleChat/commit/f43022b597737a04a250c3bb802ea71f156dfa10 aka release candidate 3.0.27, see releases
