### ISSUE TITLE
Friend joined/left format issue

### ISSUE THREAD

**Issue by atyrode** [boomboompower/ToggleChat#26]
Hello!

Hypixel changed the format for friend joining/leaving notifications so they fit the format of the newly added guildmate joining/leaving notifications.

Here's a screenshot of the new format: https://i.imgur.com/kS51uuy.png

This change of format made the friend notification toggle obsolete!

**Comment by boomboompower** [comment]
Thanks for letting me know, I'll apply a fix immediately which should be available in the action panel once it's done. 

Has the guild one changed at all?

**Comment by boomboompower** [comment]
This build is available under the following workflow. Download the file which **does not** end in -sources.jar

https://github.com/Isophene/ToggleChat/actions/runs/81991467

**Comment by atyrode** [comment]
> Has the guild one changed at all?

Assuming I didn't miss anything, they added a new notification for when a guildmate comes online or goes offline, it has the same format as the new friend notification except it says "Guild > x joined/left"

EDIT: Btw, I tried the newly compiled build (nice new gui!) but it seems like the friend option doesn't work/change anything and let the new notification pass through still. Could it be a mismatch with the ">" character?

2nd EDIT: My bad, didn't pay attention and didn't notice left/join are now separated.

Thanks for hasty fix!

**Comment by boomboompower** [comment]
The guild toggle has been added in #27 

Thank SirNapkin for the guild ones aha. Hopefully this resolves the issue
