### ISSUE TITLE
Installer will not work unless directory is already created

### ISSUE THREAD

**Issue by xcfrg** [boomboompower/ToggleChat#29]
**Describe the bug**
The installer for 3.0.1 didn't work for me, so i ran it in console using java -jar to see the error.
After I created the directory "1.8.9" in .minecraft/mods, the installer completed successfully.

**To Reproduce**
1. Run the installer without the 1.8.9 directory created in console.
2. Notice the error.
2. Create the 1.8.9 directory.
3. Run the installer again in console, no errors will be generated and installer will finish properly.

**Expected behavior**
Installer should either create the 1.8.9 directory, or put it directly into your mods folder.

**Screenshots**
![Screenshot](https://please-click-this.questionable.link/jIpgOF.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Windows, Linux] Windows
 - Mod Version: [e.g. 3.0, ??] 3.0.1
 - Minecraft Version: [e.g  1.12.2, 1.9.4, 1.8.9] 1.8.9

**Additional context**
None

**Comment by boomboompower** [comment]
@Gangster8192 can you see if this fixes the issue for you?

**Comment by xcfrg** [comment]
@boomboompower Works!
