### ISSUE TITLE
Is there a reccomended alternative to this that supports 1.16/latest? [+1]

### ISSUE THREAD

**Issue by jasikpark** [boomboompower/ToggleChat#38]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the related problem is. E.g. The mod UI blocks mw from [...] so I'd like [...] to be changed to fix that. 

I would like to be able to modify and filter my chat when on Hypixel, but while running 1.16.5/latest minecraft.

**Describe the solution you'd like**
A clear and concise description of what you want to happen. "I'd like to have the option to do ____ with the mod so I can _____"

I don't expect there to be a solution as part of this project, since it seems that the resounding opinion is "just use 1.8.9", but I'd like to be able to filter out extraneous chat messages like this, but while running 1.16.1

**Describe alternatives you've considered**

**Additional context**

**Comment by boomboompower** [comment]
> **Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the related problem is. E.g. The mod UI blocks mw from [...] so I'd like [...] to be changed to fix that.
> 
> I would like to be able to modify and filter my chat when on Hypixel, but while running 1.16.5/latest minecraft.
> 
> **Describe the solution you'd like**
> A clear and concise description of what you want to happen. "I'd like to have the option to do ____ with the mod so I can _____"
> 
> I don't expect there to be a solution as part of this project, since it seems that the resounding opinion is "just use 1.8.9", but I'd like to be able to filter out extraneous chat messages like this, but while running 1.16.1
> 
> **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context**
> Add any other context or screenshots about the feature request here.

Are you looking for 1.16.5 support on Forge? or on Fabric? I can probably whip up a quick port for either version if you'd like it

**Comment by jasikpark** [comment]
Fabric, awesome :D

**Comment by boomboompower** [comment]
> Fabric, awesome :D

A 1.16.5 edition of the mod is now available [here](https://github.com/boomboompower/ToggleChat/releases/tag/3.0.34.0) - as per the notes a few of the cosmetic features aren't available unfortunately 

I played around with it in survival and it seemed to work fine (tested a few of the guild toggles, and the separator toggle) - let me know if any of the UIs have any crashes.

I used the following to compile it, make sure you're using the correct version 😄 
```
minecraft_version=1.16.5
yarn_mappings=1.16.5+build.5
loader_version=0.11.2
fabric_version=0.32.0+1.16
```
If this means nothing to you don't worry too much, this is just for any devs out there.
