### ISSUE TITLE
Add new "/report" info message

### ISSUE THREAD

**Issue by SuperStormer** [boomboompower/ToggleChat#43]
**Is your feature request related to a problem? Please describe.**
Hypixel recently added this new message: 
![2021-09-23_18 16 06](https://user-images.githubusercontent.com/41648788/134599462-0276e426-b632-4c7a-bc0a-3c7148881ed9.png)

**Describe the solution you'd like**
Add an option to disable this message (or just add it to the preexisting watchdog option, idk).

**Describe alternatives you've considered**
Custom filter, but I think this would be applicable to others, so it should be a default filter.

**Additional context**
n/a

**Comment by SuperStormer** [comment]
The "crossteaming is not allowed" message is also missing.

**Comment by boomboompower** [comment]
> **Is your feature request related to a problem? Please describe.**
> Hypixel recently added this new message:
> ![2021-09-23_18 16 06](https://user-images.githubusercontent.com/41648788/134599462-0276e426-b632-4c7a-bc0a-3c7148881ed9.png)
> 
> **Describe the solution you'd like**
> Add an option to disable this message (or just add it to the preexisting watchdog option, idk).
> 
> **Describe alternatives you've considered**
> Custom filter, but I think this would be applicable to others, so it should be a default filter.
> 
> **Additional context**
> n/a

I'll get this added to the watchdog advertisement toggle



> The "crossteaming is not allowed" message is also missing.

I don't really want to have a built in toggle for this one, since it's a rule which they want everyone to see :P 

Feel free to make a custom toggle for that one though

**Comment by SuperStormer** [comment]
This message also:
![2021-09-25_00 30 12](https://user-images.githubusercontent.com/41648788/134759411-d84bbe6e-ccfb-4963-af67-e733008df673.png)

**Comment by boomboompower** [comment]
Implemented as a new toggle in https://github.com/boomboompower/ToggleChat/commit/554d21bf3fa3c9f052712da3dc2dc25ebbb5e86b

**Comment by boomboompower** [comment]
Available [here](https://no.boomy.wtf/?name=ToggleChat&version=3.1.1)
